### ISSUE TITLE
xmlns attribute should not probably be displayed in Update solutions versions dialog

### ISSUE THREAD

**Issue by wikiped** [dahall/IntentionalSolutionVersion#10]
Currently (version 1.1.2) Update solutions window displays `xmlns=".."` text which is not actually part of the line representing the relevant Version field (i.e. line 3 in the example below):

![image](https://user-images.githubusercontent.com/5990528/147659422-c74b8d8e-dd1b-4924-9c8f-eefdf4c488bb.png)

Actual line looks like:

`<ApplicationVersion>1.2.2.0</ApplicationVersion>`

**Comment by dahall** [comment]
I have it fixed. Once I fix a new build error with the VS2019 version, I'll publish it in 1.1.3.
