### ISSUE TITLE
Need to change last (4-th) version part

### ISSUE THREAD

**Issue by freesj** [dahall/IntentionalSolutionVersion#11]
Now it works fine with changing version from 2.12.1 to 2.12.2 for example, BUT there is 4-th part of project version (build). I really need to change version from 2.12.1.2 to 2.12.1.3.

Help please!

**Comment by dahall** [comment]
It is s a pretty big uplift to do this. The control on the form supports either 3 or 4 places, but all the parsing code would need to be updated. You're welcome to submit a PR.

**Comment by pmespace** [comment]
Unfortunately despite the fact the form shows only 3 parts it sets 4 (4th is always 0). So either it allows to set it to a real value or it just doesn't set anything inside this 4th part. Setting it messes with nuget packages (using only 3 parts). Could you please fix that ?

**Comment by dahall** [comment]
This has been added to v1.2
