### ISSUE TITLE
Empty lines should not be cleaned

### ISSUE THREAD

**Issue by eMuonTau** [dahall/IntentionalSolutionVersion#12]
When updating version info empty lines are removed. I don't know if anything else is affected but it should only touch version tags.

Thanks

**Comment by dahall** [comment]
This happens with XML files and is an issue with the XmlWriter in C#. If you know a way around it, I'm open.

**Comment by eMuonTau** [comment]
Can you try `xmlDoc.PreserveWhitespace = true;` before `xmlDoc.Load()`?

https://learn.microsoft.com/en-us/dotnet/api/system.xml.xmldocument.preservewhitespace?view=netframework-4.8

**Comment by dahall** [comment]
Fixed in 1.2.1

**Comment by eMuonTau** [comment]
Thanks.

FYI: 1.2.1 is not in source control.

**Comment by dahall** [comment]
Sorry. I just pushed it.
