### ISSUE TITLE
4th segment added to version regardless of 'Use 4th version segment' setting.

### ISSUE THREAD

**Issue by braydon-1243** [dahall/IntentionalSolutionVersion#13]
### The latest release (1.2.0) changed some functionality...

BTW, I love this tool and really appreciate all that you do! This makes our versioning much easier especially since we use `VersionPrefix` in our `.csproj` files (which allows us to specify a version suffix from our pipeline).

This is the Version that we are wanting to upgrade to 2.11.0 (this is a snippet from the `.csproj` file)
`<VersionPrefix>2.10.0</VersionPrefix>`

After running the tool with these settings:
![image](https://github.com/dahall/IntentionalSolutionVersion/assets/25259374/990d2b14-b49a-48aa-ad12-f2790c17d7f6)
 
These are the results after running the tool with those setting:
`<VersionPrefix>2.11.0.0</VersionPrefix>`

As you can see it appended on a `.0` to the version number. I did not expect this behavior since I did not select `Use 4th version segment`.

**Comment by dahall** [comment]
Good to know this exception. There is code that is supposed to match existing format to the new one, but this seems to be failing.

**Comment by dahall** [comment]
Fixed, hopefully for your case too, in v1.2.1 (posting today)
