### ISSUE TITLE
Not Recognizing Existing Version Info

### ISSUE THREAD

**Issue by kyleherzog** [dahall/IntentionalSolutionVersion#14]
Recently (last month or two), the extension quit recognizing existing version information in my projects. Everything is recognized as version number 0.0.0.  It used to display the version numbers in the .csproj files and would show both the values in the ApplicationVersion and Version tags.  I'm using .NET Standard  and .NET Core projects in Visual Studio 2022.

**Comment by kyleherzog** [comment]
I'm using version 1.2.0.

**Comment by dahall** [comment]
This must be a bug with the logic changes made in 1.2. Please roll back to the previous version while I can fix the issue. Thanks for the detail.

**Comment by kyleherzog** [comment]
My projects only set 2 segments of the version number. I just tested switching to 3 segments, that makes them show up.

**Comment by dahall** [comment]
Fixed, hopefully for your case too, in v1.2.1 (posting today)
