### ISSUE TITLE
Error when trying to update version info

### ISSUE THREAD

**Issue by jnothstine** [dahall/IntentionalSolutionVersion#2]
I get an error as soon as I press the menu item to update the version info.

I am using:
* Visual Studio 2017 with a couple of important plugins that may possibly affect the world.
* ReSharper
* Vsvim
* Supercharger

I have tried it on three solutions and get the same problem:

Solution 1
 * Two csproj projects
 * Both projects are class library projects
 * Both projects are .NET Framework 4.6.1
 * Both project names have periods in the name like "x.y.z"

Solution 2
 * Several csproj project projects
 * Some projects are nested under solution folders
 * All projects are .NET Framework 4.6.1
 * All project files are named similar to Solution 1

Solution 3
 * Three csproj projects
 * Simple names in the projects (no periods in the name)
 * .NET Framework 4.6.1

The code is proprietary so, unfortunately, I can not make it available. :(

I really want this to work so I can try to do different things to help.  If you can provide a version with lots of debug lines or something, I will be more than happy to install it and get some output for you.  I have done that before to help plugin developers.

**Comment by dahall** [comment]
Thank you for the offer, troubleshooting advice, and problem detail. I will try to get a debugable version posted to you in the next 24 hours.

**Comment by dahall** [comment]
Attached is a zip file containing an updated VSIX file to install a debug version of the extension. If a message shows prior to showing the edit form, please let me know what type of project is listed and how it fits in the hierarchy (under a project, solution folder, etc.). The only place in the code there is a dictionary add is when enumerating all the projects where I've added the handler.
[IntentionalSolutionVersion.zip](https://github.com/dahall/IntentionalSolutionVersion/files/1735037/IntentionalSolutionVersion.zip)

**Comment by jnothstine** [comment]
I have attached three screen shots from one project (same thing happens on others)

  1.  Your new screen that says a problem exists
  2.  The next screen, from your tool
  3.  The third screen is my solution explorer for the same solution that gave me this error message.

I hope this helps get some useful information for you and let me know if there is more you want me to do.  Am always happy to help.

**Comment by jnothstine** [comment]
Just noticed an enhancement request.  ☺  I frequently set beta versions in my solutions until something is ready to push to production.  We set version numbers like:  1.2.3-beta01.  That is where I do the most change sets (probably a couple of times a day) where this would be the most beneficial.  Of course, the AssemblyInfo.cs AsseeblyVersion and AssemblyFileVersion would stay as 1.2.3 but the nuspec file would need 1.2.3-beta01.  Here is an example from a screen shot from your tool.  Note the first line is from AssemblyInfo.cs and the highlighted line is from my nuspec file.  When updating, this I will go to 4.6.1-WebApi-Phase203 and leave the AssemblyFileVersion alone.  When it goes to production, both files will become 4.7.0.

[cid:image004.png@01D3A99B.025E0EE0]

**Comment by dahall** [comment]
The images didn’t come through in the email or on the issues page. Will you reply to this with them? BTW, thanks for your help.

**Comment by dahall** [comment]
I think if you go to the site [https://github.com/dahall/IntentionalSolutionVersion/issues/2](https://github.com/dahall/IntentionalSolutionVersion/issues/2) and edit or repost, the images will come through. Email seems to be the problem.

**Comment by jnothstine** [comment]
Here are the three images for the first message.

![image](https://user-images.githubusercontent.com/779555/36412353-1db037ba-15d7-11e8-9076-3a9f34acc240.png)

![image](https://user-images.githubusercontent.com/779555/36412385-38d76e46-15d7-11e8-8513-abe5e61488cd.png)

![image](https://user-images.githubusercontent.com/779555/36412404-479c8f60-15d7-11e8-918b-46737807a0e4.png)

**Comment by jnothstine** [comment]
Here is the image from my request to add beta versions

![image](https://user-images.githubusercontent.com/779555/36412639-4f49d8d4-15d8-11e8-9bd2-0223c5d0286e.png)

**Comment by dahall** [comment]
Will you describe what is in the .nuget folder in your solution?

**Comment by jnothstine** [comment]
Just one file is in that folder.  Nuget.config.  Here is the contents of that file.

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>
  <packageSources>
    <add key="Waterstreet-Development" value="http://wsbf-nuget:81/nuget/Development" />
    <add key="Waterstreet-Tools" value="http://wsbf-nuget:81/nuget/Tools" />
    <add key="NuGet" value="http://nuget.org/api/v2" />
  </packageSources>
</configuration>

**Comment by dahall** [comment]
Good news. I believe I found and corrected the error. It had to do with improper handling of solution folders with only files in them. Give this attached version a try: [IntentionalSolutionVersion.zip](https://github.com/dahall/IntentionalSolutionVersion/files/1741798/IntentionalSolutionVersion.zip). You will have to manually uninstall the prior VSIX under "Tools | Extensions and Updates", restart VS17, and install this one. I have also, to partially answer your enhancement request, made the extension only search and replace the first 3 digit pairs leaving the 4th alone. If I'm reading your request correctly, this should allow you to update all the major.minor.build sequences using the tool and then set the revision value manually. Right-clicking on the file in the dialog will allow you to open the corresponding file directly to make this edit.

**Comment by jnothstine** [comment]
Just did a quick test and that seems to have fixed the problem.

The change for the enhancement request is a nice step and will help.  I have one solution that has five projects with nuspec files that I have to keep in sync.  This is where your tool will be most beneficial is when I can easily update the nuspec version numbers in one place.

Thanks for jumping on the issue and enhancement request so fast.  I love that kind of support for a tool!

**Comment by dahall** [comment]
Thanks for your testing. I am updating the releases with this new code then. If possible, would you mind updating your 1-star rating on Visual Studio Marketplace so that others will be less deterred to try it?

**Comment by jnothstine** [comment]
Done.  I also added some text about the great response you have given me on working through the problem.
