### ISSUE TITLE
Visual Studio MPF 15.0 Missing on VS2019

### ISSUE THREAD

**Issue by kyleherzog** [dahall/IntentionalSolutionVersion#3]
When trying to install this extension in Visual Studio 2019, I get a message that says "The following references must be present before installation can continue: Visual Studio MPF 15.0" and it does not allow me to install the extension.

**Comment by dahall** [comment]
I've just pushed an update (1.0.6) with a few VS2019 bug fixes. Please update and let me know if your issue is resolved.

**Comment by kyleherzog** [comment]
It installs correctly now. Thanks!
