### ISSUE TITLE
Visual Studio 2022 Compatibility

### ISSUE THREAD

**Issue by kyleherzog** [dahall/IntentionalSolutionVersion#5]
Any plans to make this extension available for Visual Studio 2022?

**Comment by dahall** [comment]
Yes, but it will be a few weeks. I always welcome PRs!

**Comment by dahall** [comment]
Done. Please find it in Marketplace as [Intentional Solution Version Editor VS2022](https://marketplace.visualstudio.com/items?itemName=dahall.IntentionalSolutionVersion2022).

**Comment by kyleherzog** [comment]
I get a page not found message with that link and am not finding the extension searching for it directly in VS2022.

**Comment by dahall** [comment]
Sorry. Try it again please.

**Comment by kyleherzog** [comment]
got it now. Thanks!
