### ISSUE TITLE
Fails on start (VS 2022)

### ISSUE THREAD

**Issue by freesj** [dahall/IntentionalSolutionVersion#6]
![image](https://user-images.githubusercontent.com/20525039/142437204-e8522c49-59b6-47c3-9f57-86aa65ac4e4d.png)

**Comment by dahall** [comment]
Will you provide more detail about when you see this error? Start of what? Is a solution loaded?

**Comment by freesj** [comment]
I see this error "on start" of extension - at the moment when i click "Udate Version Info..." item in VS 2022 Tools menu. All projects of my solution are placed in a virtual folders

**Comment by dahall** [comment]
Thank you for that detail. So as I understand it, you have a solution and all top level elements in that solution are virtual folders under which you have your projects and files?

**Comment by freesj** [comment]
Yes, i have virtual folder as top-level item and other virtual folders in it, where my projects are placed
