### ISSUE TITLE
Fails on start #2 (VS 2022)

### ISSUE THREAD

**Issue by freesj** [dahall/IntentionalSolutionVersion#7]
![image](https://user-images.githubusercontent.com/20525039/144200111-55e0a999-9057-4b7d-a3db-001e71467eae.png)
Error message changed! But problem is not solved - still fails on start...

Google says that in english error looks like "System.InvalidCastException"

**Comment by dahall** [comment]
Hm. Is your project publicly available or are you able to send it to me? I created a test solution with two virtual folders at the root and a single project within each. The extension worked under VS2022 under that config.

**Comment by dahall** [comment]
Also, please confirm you're using version 1.1.2.

**Comment by freesj** [comment]
I also created a test solution with a large number of virtual folders and your extension works fine in it! Apparently the problem is in my working solution. Unfortunately, I can't give it to you. I can only post a screenshot of the structure of the solution (most of it). Anyway - thanks for trying to help.
![image](https://user-images.githubusercontent.com/20525039/144566812-a0b91e7c-7437-43a6-b574-bba87ce3d744.png)

**Comment by freesj** [comment]
and of course I'm using version 1.1.2

**Comment by wikiped** [comment]
I have version 1.1.3 on VS 2022 (Version 17.0.5) - no problems so far.

**Comment by freesj** [comment]
Still have the same problem with the same error message....

**Comment by dahall** [comment]
I think I have a fix, but I cannot duplicate a solution that causes the error under 1.1.3. I am posting the update here in hopes you can test and confirm it is working. Extract the VSIX from the attached ZIP file and launch it to install.

[IntentionalSolutionVersion2022.zip](https://github.com/dahall/IntentionalSolutionVersion/files/7926873/IntentionalSolutionVersion2022.zip)

**Comment by dahall** [comment]
@freesj Any luck?

**Comment by freesj** [comment]
Hi.
Still not working. Error message changed:

---------------------------
Microsoft Visual Studio
---------------------------

Duplicate projects. Please report as issue and include this text. (Press Ctrl-C to capture)
OLD

Found projects:C:\dev\ASUNO Sunrise\Main\Source\CoreLib\CoreLib.csproj
C:\dev\ASUNO Sunrise\Main\Source\CoreLib.Test\CoreLib.Test.csproj
.nuget
C:\dev\ASUNO Sunrise\Main\Source\ServerLib\ServerLib.csproj
C:\dev\ASUNO Sunrise\Main\Source\USLib\USLib.csproj
C:\dev\ASUNO Sunrise\Main\Source\UnitsServer\UnitsServer.csproj
C:\dev\ASUNO Sunrise\Main\Source\RepLib\RepLib.csproj
C:\dev\ASUNO Sunrise\Main\Source\SunriseWebService\SunriseWebService.csproj
Solution Items
SQL
OLD
C:\dev\ASUNO Sunrise\Main\Source\UDM\UDM.csproj
C:\dev\ASUNO Sunrise\Main\Source\CalcUnitModule\CalcUnitModule.csproj
C:\dev\ASUNO Sunrise\Main\Source\CoreApp\CoreApp.csproj
C:\dev\ASUNO Sunrise\Main\Source\Module.Systems\Module.Systems.csproj
C:\dev\ASUNO Sunrise\Main\Source\App.Services\App.Services.csproj
C:\dev\ASUNO Sunrise\Main\Source\UnitManagerModule\UnitManagerModule.csproj
C:\dev\ASUNO Sunrise\Main\Source\CoreSLib\CoreSLib.csproj
C:\dev\ASUNO Sunrise\Main\Source\ResLib\ResLib.csproj
C:\dev\ASUNO Sunrise\Main\Source\MassTransferData\MassTransferData.csproj
C:\dev\ASUNO Sunrise\Main\Source\YartBridge\YartBridge.csproj
C:\dev\ASUNO Sunrise\Main\Source\TemplateCreator\TemplateCreator.csproj
C:\dev\ASUNO Sunrise\Main\Source\AlgoRitmer\AlgoRitmer\AlgoRitmer.csproj
C:\dev\ASUNO Sunrise\Main\Source\AsunoRestarter\AsunoRestarter.csproj
C:\dev\ASUNO Sunrise\Main\Source\MassChanger\MassChanger.csproj
C:\dev\ASUNO Sunrise\Main\Source\KAdapter.Test\KAdapter.Test.csproj
C:\dev\ASUNO Sunrise\Main\Source\FakeAdapter\FakeAdapter.csproj
C:\dev\ASUNO Sunrise\Main\Source\FakeServer\FakeServer.csproj
C:\dev\ASUNO Sunrise\Main\Source\FakeServerCore\FakeServerCore.csproj
C:\dev\ASUNO Sunrise\Main\Source\CAdapter\CAdapter.csproj
C:\dev\ASUNO Sunrise\Main\Source\AutoSyncTimeForAdapterK\AutoSyncTimeForAdapterK.csproj
C:\dev\ASUNO Sunrise\Main\Source\KAdapter\KAdapter.csproj
C:\dev\ASUNO Sunrise\Main\Source\StructureNavModule\StructureNavModule.csproj
C:\dev\ASUNO Sunrise\Main\Source\TimeModule\TimeModule.csproj
C:\dev\ASUNO Sunrise\Main\Source\UnitsManagerModule\UnitsManagerModule.csproj
C:\dev\ASUNO Sunrise\Main\Source\UsersModule\UsersModule.csproj
C:\dev\ASUNO Sunrise\Main\Source\GeoViewerModule\GeoViewerModule.csproj
C:\dev\ASUNO Sunrise\Main\Source\SchedulerModule\SchedulerModule.csproj
C:\dev\ASUNO Sunrise\Main\Source\UnitViewerModule\UnitViewerModule.csproj
C:\dev\ASUNO Sunrise\Main\Source\CurrentAlarmListModule\CurrentAlarmListModule.csproj
C:\dev\ASUNO Sunrise\Main\Source\AlarmArchiveModule\AlarmArchiveModule.csproj
C:\dev\ASUNO Sunrise\Main\Source\SimplAnalysisModule\SimplAnalysisModule.csproj
C:\dev\ASUNO Sunrise\Main\Source\AuditModule\AuditModule.csproj
C:\dev\ASUNO Sunrise\Main\Source\GroupControlModule\GroupControlModule.csproj
C:\dev\ASUNO Sunrise\Main\Source\MainFrameModule\MainFrameModule.csproj
C:\dev\ASUNO Sunrise\Main\Source\AWPApplication\AWPApplication.csproj
C:\dev\ASUNO Sunrise\Main\Source\RDService\RDService.csproj
C:\dev\ASUNO Sunrise\Main\Source\SunriseWebApp\SunriseWebApp.csproj
C:\dev\ASUNO Sunrise\Main\Source\CoreLibExt\CoreLibExt.csproj

---------------------------
ОК   
---------------------------

**Comment by freesj** [comment]
Wow! It was Info message, not error! When I pressed “OK” button – extension worked perfectly! Thank you!

**Comment by dahall** [comment]
It appears it had a problem with a solution item named "OLD" in your solution. Can you provide some details about that item so I can add in support or handle the error? What is just a solution folder that you have in your solution twice?

**Comment by freesj** [comment]
![image](https://user-images.githubusercontent.com/20525039/151370973-eaf3319a-97ec-4297-b448-ca59f8065c7f.png)

You are wright - there are 2 folders "OLD" in solution (see picture)

**Comment by dahall** [comment]
Thanks. I've made a very minor change that will be in the release that should circumvent the error you're seeing. If you want it, you'll need to uninstall the extension manually and then pull it again from Extension Manager or Visual Studio Marketplace.

I really appreciate your help in identifying and correcting this problem!

**Comment by freesj** [comment]
Thank you for your help! This is a very necessary extension for me, which has no analogues in VS2022
