### ISSUE TITLE
Invalid update of PackageReference Version

### ISSUE THREAD

**Issue by OJacot-Descombes** [dahall/IntentionalSolutionVersion#8]
In the project files the version of referenced NuGet packages is changed. This messes up the referenced NuGet packes. This version number must be managed by the NuGet package Manager.
```
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite">
      <Version>2.2.6</Version>     <==== DO NOT CHANGE THIS!
    </PackageReference>
```
I expect this tool to update the AssemblyVersion and AssemblyFileVersion. I.e., the version number I publish, not imported version numbers.

**Comment by dahall** [comment]
You can deselect these entries in the list and not include them. Their inclusion was one of the early requests as an alternative to PackageManager.

**Comment by dahall** [comment]
Another workaround may be to use the syntax like below that will not get picked up by the extension:
```xml
<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.2.6" />
```
