### ISSUE TITLE
Comment lines should be ignored

### ISSUE THREAD

**Issue by wikiped** [dahall/IntentionalSolutionVersion#9]
Thank you for the extension. I appreciate it's transparency about where the changes are being made.

I noticed, however, that If `AssemblyInfo.cs` contains commented lines and they are before non-commented line - the commented line is displayed and changed instead of actual line:

```cs
// [assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyVersion("1.1.1.0")]
```

Only the first line will be displayed in `Update solution versions` window and after changing the version it will be the only line that changed.

**Comment by dahall** [comment]
I have it fixed. Once I fix a new build error with the VS2019 version, I'll publish it in 1.1.3.
